apiVersion: apps/v1
kind: Deployment
metadata:
   name: ibmbluehackapp
spec:
   replicas: 5
   selector:
      matchLabels:
          app: ibmbluehack
   template:
       metadata:
          labels: 
            app: ibmbluehack
       spec:
         containers:
         - name: ibmbluehack
           image: gowthamshankar9/ibmbluehack
           ports:
           - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
     name: ibmbluehackservice
spec:
  selector:
     app: ibmbluehack
  type: NodePort
  ports:
  - port: 8005
    nodePort: 30080
  

          